// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use a dummy URL during build if DATABASE_URL is not set
    // This allows `prisma generate` to run without a real database
    url: env("DATABASE_URL") || "postgresql://placeholder:placeholder@localhost:5432/placeholder",
  },
});
