module.exports=[37936,(a,b,c)=>{"use strict";Object.defineProperty(c,"__esModule",{value:!0}),Object.defineProperty(c,"registerServerReference",{enumerable:!0,get:function(){return d.registerServerReference}});let d=a.r(11857)},13095,(a,b,c)=>{"use strict";function d(a){for(let b=0;b<a.length;b++){let c=a[b];if("function"!=typeof c)throw Object.defineProperty(Error(`A "use server" file can only export async functions, found ${typeof c}.
Read more: https://nextjs.org/docs/messages/invalid-use-server-value`),"__NEXT_ERROR_CODE",{value:"E352",enumerable:!1,configurable:!0})}}Object.defineProperty(c,"__esModule",{value:!0}),Object.defineProperty(c,"ensureServerEntryExports",{enumerable:!0,get:function(){return d}})},63707,a=>a.a(async(b,c)=>{try{var d=a.i(37936),e=a.i(77607);a.i(40522);var f=a.i(77419),g=a.i(13095),h=b([e]);async function i(a,b){try{await (0,e.signIn)("credentials",b)}catch(a){if(a instanceof f.AuthError)if("CredentialsSignin"===a.type)return"Invalid credentials.";else return"Something went wrong.";throw a}}async function j(){await (0,e.signOut)()}[e]=h.then?(await h)():h,(0,g.ensureServerEntryExports)([i,j]),(0,d.registerServerReference)(i,"607051c4334dde25deecd5a7467ce9cd3142e1efc7",null),(0,d.registerServerReference)(j,"00d407b4cb47e601dfebbf78dd230a8e4c5a7b9fcc",null),a.s(["authenticate",()=>i,"logout",()=>j]),c()}catch(a){c(a)}},!1),83454,a=>a.a(async(b,c)=>{try{var d=a.i(37936),e=a.i(18558),f=a.i(66518),g=a.i(43676),h=a.i(13095),i=b([f,g]);async function j(a){let{tenant:b}=await (0,g.requireTenantMembership)(),c=a.get("pageId"),d=a.get("metaTitle")||null,h=a.get("metaDescription")||null,i=a.get("metaKeywords")||null,j=a.get("ogImage")||null;if(!c)throw Error("Page ID is required");if(!await f.prisma.sitePage.findFirst({where:{id:c,tenantId:b.id}}))throw Error("Page not found");await f.prisma.sitePage.update({where:{id:c},data:{metaTitle:d,metaDescription:h,metaKeywords:i,ogImage:j}}),await f.prisma.auditLog.create({data:{tenantId:b.id,action:"PAGE_SEO_UPDATED",entity:"SitePage",entityId:c,metadata:{metaTitle:d,metaDescription:h}}}),(0,e.revalidatePath)("/builder"),(0,e.revalidatePath)(`/builder/seo/${c}`)}async function k(){let{tenant:a}=await (0,g.requireTenantMembership)(),b=await f.prisma.sitePage.findMany({where:{tenantId:a.id},select:{path:!0,updatedAt:!0}}),c=await f.prisma.tenant.findUnique({where:{id:a.id},include:{domains:!0}}),d=c?.domains[0]?.domain||`${a.slug}.yoursaas.com`;return`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${b.map(a=>`  <url>
    <loc>https://${d}${a.path}</loc>
    <lastmod>${a.updatedAt.toISOString()}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>${"/"===a.path?"1.0":"0.8"}</priority>
  </url>`).join("\n")}
</urlset>`}[f,g]=i.then?(await i)():i,(0,h.ensureServerEntryExports)([j,k]),(0,d.registerServerReference)(j,"40351321a71ed1fa232387e5916b9a1985c383e7c5",null),(0,d.registerServerReference)(k,"009e74c02313a0e65c54903fddc65cb069f17d0db1",null),a.s(["generateSitemap",()=>k,"updatePageSEO",()=>j]),c()}catch(a){c(a)}},!1),78524,a=>a.a(async(b,c)=>{try{var d=a.i(63707),e=a.i(83454),f=b([d,e]);[d,e]=f.then?(await f)():f,a.s([]),c()}catch(a){c(a)}},!1),54170,a=>a.a(async(b,c)=>{try{var d=a.i(78524),e=a.i(63707),f=a.i(83454),g=b([d,e,f]);[d,e,f]=g.then?(await g)():g,a.s(["009e74c02313a0e65c54903fddc65cb069f17d0db1",()=>f.generateSitemap,"00d407b4cb47e601dfebbf78dd230a8e4c5a7b9fcc",()=>e.logout,"40351321a71ed1fa232387e5916b9a1985c383e7c5",()=>f.updatePageSEO]),c()}catch(a){c(a)}},!1)];

//# sourceMappingURL=_fe524ebc._.js.map