// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/billing" | "/admin/features" | "/admin/plans" | "/admin/tenants/[tenantId]/users" | "/analytics" | "/automation" | "/builder" | "/builder/media" | "/builder/seo/[pageId]" | "/builder/templates" | "/crm" | "/crm/leads" | "/crm/leads/[id]" | "/crm/today" | "/finance" | "/finance/expenses" | "/finance/invoices" | "/finance/invoices/new" | "/finance/reports" | "/hr" | "/hr/attendance" | "/hr/employees" | "/hr/leave" | "/hr/payroll" | "/inventory" | "/inventory/products" | "/inventory/purchase-orders" | "/inventory/stock-movements" | "/inventory/suppliers" | "/login" | "/offline" | "/onboarding" | "/projects" | "/projects/[projectId]" | "/projects/[projectId]/edit" | "/projects/new" | "/settings" | "/settings/audit" | "/settings/billing" | "/settings/branding" | "/settings/lead-fields" | "/settings/permissions" | "/settings/roles" | "/settings/team" | "/site/[[...slug]]" | "/tasks" | "/tasks/[taskId]/edit" | "/workspace"
type AppRouteHandlerRoutes = "/api/audit/export" | "/api/invoices/[invoiceId]/download" | "/api/webhooks/stripe" | "/sitemap.xml"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/analytics" | "/automation" | "/builder" | "/crm" | "/finance" | "/hr" | "/inventory" | "/projects" | "/settings" | "/tasks"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/billing": {}
  "/admin/features": {}
  "/admin/plans": {}
  "/admin/tenants/[tenantId]/users": { "tenantId": string; }
  "/analytics": {}
  "/api/audit/export": {}
  "/api/invoices/[invoiceId]/download": { "invoiceId": string; }
  "/api/webhooks/stripe": {}
  "/automation": {}
  "/builder": {}
  "/builder/media": {}
  "/builder/seo/[pageId]": { "pageId": string; }
  "/builder/templates": {}
  "/crm": {}
  "/crm/leads": {}
  "/crm/leads/[id]": { "id": string; }
  "/crm/today": {}
  "/finance": {}
  "/finance/expenses": {}
  "/finance/invoices": {}
  "/finance/invoices/new": {}
  "/finance/reports": {}
  "/hr": {}
  "/hr/attendance": {}
  "/hr/employees": {}
  "/hr/leave": {}
  "/hr/payroll": {}
  "/inventory": {}
  "/inventory/products": {}
  "/inventory/purchase-orders": {}
  "/inventory/stock-movements": {}
  "/inventory/suppliers": {}
  "/login": {}
  "/offline": {}
  "/onboarding": {}
  "/projects": {}
  "/projects/[projectId]": { "projectId": string; }
  "/projects/[projectId]/edit": { "projectId": string; }
  "/projects/new": {}
  "/settings": {}
  "/settings/audit": {}
  "/settings/billing": {}
  "/settings/branding": {}
  "/settings/lead-fields": {}
  "/settings/permissions": {}
  "/settings/roles": {}
  "/settings/team": {}
  "/site/[[...slug]]": { "slug"?: string[]; }
  "/sitemap.xml": {}
  "/tasks": {}
  "/tasks/[taskId]/edit": { "taskId": string; }
  "/workspace": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/analytics": never
  "/automation": never
  "/builder": never
  "/crm": never
  "/finance": never
  "/hr": never
  "/inventory": never
  "/projects": never
  "/settings": never
  "/tasks": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
