// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/admin/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/billing">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/features/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/features">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/features/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/plans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/plans">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/plans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/tenants/[tenantId]/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tenants/[tenantId]/users">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/tenants/[tenantId]/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../../src/app/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/automation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/automation">> = Specific
  const handler = {} as typeof import("../../../src/app/automation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/builder/media/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/builder/media">> = Specific
  const handler = {} as typeof import("../../../src/app/builder/media/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/builder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/builder">> = Specific
  const handler = {} as typeof import("../../../src/app/builder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/builder/seo/[pageId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/builder/seo/[pageId]">> = Specific
  const handler = {} as typeof import("../../../src/app/builder/seo/[pageId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/builder/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/builder/templates">> = Specific
  const handler = {} as typeof import("../../../src/app/builder/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/crm/leads/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/crm/leads/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/crm/leads/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/crm/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/crm/leads">> = Specific
  const handler = {} as typeof import("../../../src/app/crm/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/crm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/crm">> = Specific
  const handler = {} as typeof import("../../../src/app/crm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/crm/today/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/crm/today">> = Specific
  const handler = {} as typeof import("../../../src/app/crm/today/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/finance/expenses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/expenses">> = Specific
  const handler = {} as typeof import("../../../src/app/finance/expenses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/finance/invoices/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/invoices/new">> = Specific
  const handler = {} as typeof import("../../../src/app/finance/invoices/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/finance/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/invoices">> = Specific
  const handler = {} as typeof import("../../../src/app/finance/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance">> = Specific
  const handler = {} as typeof import("../../../src/app/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/finance/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance/reports">> = Specific
  const handler = {} as typeof import("../../../src/app/finance/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/hr/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/attendance">> = Specific
  const handler = {} as typeof import("../../../src/app/hr/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/hr/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/employees">> = Specific
  const handler = {} as typeof import("../../../src/app/hr/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/hr/leave/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/leave">> = Specific
  const handler = {} as typeof import("../../../src/app/hr/leave/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/hr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr">> = Specific
  const handler = {} as typeof import("../../../src/app/hr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/hr/payroll/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/payroll">> = Specific
  const handler = {} as typeof import("../../../src/app/hr/payroll/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory">> = Specific
  const handler = {} as typeof import("../../../src/app/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/inventory/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/products">> = Specific
  const handler = {} as typeof import("../../../src/app/inventory/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/inventory/purchase-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/purchase-orders">> = Specific
  const handler = {} as typeof import("../../../src/app/inventory/purchase-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/inventory/stock-movements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/stock-movements">> = Specific
  const handler = {} as typeof import("../../../src/app/inventory/stock-movements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/inventory/suppliers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/suppliers">> = Specific
  const handler = {} as typeof import("../../../src/app/inventory/suppliers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/offline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offline">> = Specific
  const handler = {} as typeof import("../../../src/app/offline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../../src/app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/projects/[projectId]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]/edit">> = Specific
  const handler = {} as typeof import("../../../src/app/projects/[projectId]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/projects/[projectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[projectId]">> = Specific
  const handler = {} as typeof import("../../../src/app/projects/[projectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/projects/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/new">> = Specific
  const handler = {} as typeof import("../../../src/app/projects/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../../src/app/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/audit">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/billing">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/branding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/branding">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/branding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/lead-fields/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/lead-fields">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/lead-fields/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/permissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/permissions">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/permissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/roles">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/team">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/site/[[...slug]]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/site/[[...slug]]">> = Specific
  const handler = {} as typeof import("../../../src/app/site/[[...slug]]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tasks/[taskId]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tasks/[taskId]/edit">> = Specific
  const handler = {} as typeof import("../../../src/app/tasks/[taskId]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tasks">> = Specific
  const handler = {} as typeof import("../../../src/app/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace">> = Specific
  const handler = {} as typeof import("../../../src/app/workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/audit/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/export">> = Specific
  const handler = {} as typeof import("../../../src/app/api/audit/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/invoices/[invoiceId]/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invoices/[invoiceId]/download">> = Specific
  const handler = {} as typeof import("../../../src/app/api/invoices/[invoiceId]/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/webhooks/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/webhooks/stripe">> = Specific
  const handler = {} as typeof import("../../../src/app/api/webhooks/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/sitemap.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sitemap.xml">> = Specific
  const handler = {} as typeof import("../../../src/app/sitemap.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/analytics/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../../src/app/analytics/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/automation/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/automation">> = Specific
  const handler = {} as typeof import("../../../src/app/automation/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/builder/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/builder">> = Specific
  const handler = {} as typeof import("../../../src/app/builder/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/crm/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/crm">> = Specific
  const handler = {} as typeof import("../../../src/app/crm/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/finance/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/finance">> = Specific
  const handler = {} as typeof import("../../../src/app/finance/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/hr/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/hr">> = Specific
  const handler = {} as typeof import("../../../src/app/hr/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/inventory/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/inventory">> = Specific
  const handler = {} as typeof import("../../../src/app/inventory/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/projects/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../../src/app/projects/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tasks/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/tasks">> = Specific
  const handler = {} as typeof import("../../../src/app/tasks/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
